# -*- coding: utf-8 -*-
"""Image Classifier Using CNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D8uMICwxw7i9kU-n8Op82-5cMYgZYPzW
"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

!kaggle datasets download -d salader/dogs-vs-cats

import zipfile
zip_ref = zipfile.ZipFile('/content/dogs-vs-cats.zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, BatchNormalization, Dropout

#Generators
train_ds = keras.utils.image_dataset_from_directory(
    directory = '/content/train',
    labels="inferred",
    label_mode="int",
    batch_size=32,
    image_size=(256, 256)
)

test_ds = keras.utils.image_dataset_from_directory(
    directory = '/content/test',
    labels="inferred",
    label_mode="int",
    batch_size=32,
    image_size=(256, 256)
)

#Normalization

def normal(image, label):
  image = tf.cast(image/255, tf.float32)
  return image, label

train_ds = train_ds.map(normal)
test_ds = test_ds.map(normal)

model = Sequential()

model.add(Conv2D(32, kernel_size=(3,3), padding='valid', activation='relu', input_shape=(256,256,3)))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2), strides=2, padding='valid'))

model.add(Conv2D(64, kernel_size=(3,3), padding='valid', activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2), strides=2, padding='valid'))

model.add(Flatten())

model.add(Dense(128, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(1, activation='sigmoid'))

model.summary()

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(train_ds, epochs=10, validation_data=test_ds)

import matplotlib.pyplot as plt

plt.plot(model.history.history['accuracy'], color = 'red', label='train')
plt.plot(model.history.history['val_accuracy'], color = 'blue', label='test')
plt.legend()
plt.show()

plt.plot(model.history.history['loss'], color = 'red', label='train')
plt.plot(model.history.history['val_loss'], color = 'blue', label='test')
plt.legend()
plt.show()

import cv2

test_img = cv2.imread('/content/dog.jpg')

plt.imshow(test_img)

test_img.shape

test_img = cv2.resize(test_img, (256,256))

test_img = test_img.reshape((1,256,256,3))

model.predict(test_img)

test_img = cv2.imread('/content/cat.jpg')

plt.imshow(test_img)

test_img = cv2.resize(test_img, (256,256))

test_img = test_img.reshape((1,256,256,3))

model.predict(test_img)